version: '3.9'

services:
  db:
    container_name: "simple-market-postgresql"
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Paroli1!
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - simple-market_postgres:/var/lib/postgresql/data

  localstack:
    container_name: "simple-market-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  simple-market_postgres:
