version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Paroli1!
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - snap_postgres:/var/lib/postgresql/data

volumes:
  snap_postgres:
