services:
  db:
    container_name: "simple-market-postgresql"
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Paroli1!
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - simple-market_postgres:/var/lib/postgresql/data

  #local stack
  localstack:
    container_name: "simple-market-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
   
  # Jaeger service
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"  # Jaeger agent (UDP port)
      - "16686:16686"    # Jaeger UI
      - "14268:14268"    # Jaeger Collector HTTP (for trace submission)
      - "14250:14250"    # Jaeger gRPC Collector
      - "14269:14269"    # Collector admin
      - "9411:9411"      # Zipkin compatible service 
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"      # OTLP HTTP (default OpenTelemetry port)

volumes:
  simple-market_postgres:
