global:
  evaluation_interval: 30s
  scrape_interval: 5s

scrape_configs:
  - job_name: orders-api
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:59476']